name: Auto build for windows

on: push

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup go
      uses: actions/setup-go@v3
      with:
          go-version: '1.18'
          check-latest: true
    - uses: actions/checkout@v3

    - name: Package Application
      run: go build

    - name: get config
      run: mv ./release/* ./

    - name: download WinDivert.dll
      run: |
        Invoke-WebRequest -v -o ./WinDivert.zip https://github.com/basil00/Divert/releases/download/v1.4.3/WinDivert-1.4.3-A.zip
        Expand-Archive ./WinDivert.zip -DestinationPath ./
        mv WinDivert-1.4.3-A/x86_64/WinDivert.dll ./
        
    - uses: actions/upload-artifact@v3
      with:
        name: TCPioneer
        path: |
          TCPioneer.exe
          default.conf
          install_service.bat
          remove_service.bat
          start_service.bat
          stop_service.bat
          WinDivert64.sys
          WinDivert.dll
